#!/bin/sh
#if test ! -e $1
#then
#   echo "$1 does not exist."
#   exit 1
#else
#   ls -l $1
#fi

if test ! -e "$1" ; then
   printf "There is not readable *.rec file exists in the specified path or its subdirectories \n"
   exit 1
   break
fi